; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; Test the experimental kernel ABI tweak r7-arg.
;
; RUN: llc < %s -mtriple=s390x-linux-gnu -mattr=+soft-float \
; RUN:   -mattr=+experimental-kernel-abi-r6-clobbered \
; RUN:   -mattr=+experimental-kernel-abi-r7-arg | FileCheck %s

declare void @g()
declare i64 @g6(i64, i64, i64, i64, i64, i64)
declare void @g7(i64, i64, i64, i64, i64, i32, i64)

; The sixth argument is in %r7, the seventh on the stack.
define i64 @f1(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e, i64 %f, i64 %g) {
; CHECK-LABEL: f1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lgr %r2, %r7
; CHECK-NEXT:    ag %r2, 160(%r15)
; CHECK-NEXT:    br %r14
  %s = add i64 %f, %g
  ret i64 %s
}

define i32 @f2(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e, i32 %f) {
; CHECK-LABEL: f2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lr %r2, %r7
; CHECK-NEXT:    br %r14
  ret i32 %f
}

define void @call_g7(i32 %f) {
; CHECK-LABEL: call_g7:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -168
; CHECK-NEXT:    .cfi_def_cfa_offset 328
; CHECK-NEXT:    lr %r7, %r2
; CHECK-NEXT:    lghi %r2, 1
; CHECK-NEXT:    lghi %r3, 2
; CHECK-NEXT:    lghi %r4, 3
; CHECK-NEXT:    lghi %r5, 4
; CHECK-NEXT:    lghi %r6, 5
; CHECK-NEXT:    mvghi 160(%r15), 7
; CHECK-NEXT:    brasl %r14, g7@PLT
; CHECK-NEXT:    lmg %r14, %r15, 280(%r15)
; CHECK-NEXT:    br %r14
  call void @g7(i64 1, i64 2, i64 3, i64 4, i64 5, i32 %f, i64 7)
  ret void
}

; A sibling call with six arguments.
define i64 @f3(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e, i64 %f) {
; CHECK-LABEL: f3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    lgr %r0, %r4
; CHECK-NEXT:    lgr %r1, %r3
; CHECK-NEXT:    lgr %r14, %r2
; CHECK-NEXT:    lgr %r2, %r7
; CHECK-NEXT:    lgr %r3, %r6
; CHECK-NEXT:    lgr %r4, %r5
; CHECK-NEXT:    lgr %r5, %r0
; CHECK-NEXT:    lgr %r6, %r1
; CHECK-NEXT:    lgr %r7, %r14
; CHECK-NEXT:    lmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    jg g6@PLT
  %r = tail call i64 @g6(i64 %f, i64 %e, i64 %d, i64 %c, i64 %b, i64 %a)
  ret i64 %r
}

; %r7 is call-clobbered.
define i64 @f4(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e, i64 %f) {
; CHECK-LABEL: f4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r13, %r15, 104(%r15)
; CHECK-NEXT:    .cfi_offset %r13, -56
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lgr %r13, %r7
; CHECK-NEXT:    brasl %r14, g@PLT
; CHECK-NEXT:    lgr %r2, %r13
; CHECK-NEXT:    lmg %r13, %r15, 264(%r15)
; CHECK-NEXT:    br %r14
  call void @g()
  ret i64 %f
}

; The call-saved GPRs are %r8-%r15.
define void @f5(ptr %p) {
; CHECK-LABEL: f5:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r8, %r15, 64(%r15)
; CHECK-NEXT:    .cfi_offset %r8, -96
; CHECK-NEXT:    .cfi_offset %r9, -88
; CHECK-NEXT:    .cfi_offset %r10, -80
; CHECK-NEXT:    .cfi_offset %r11, -72
; CHECK-NEXT:    .cfi_offset %r12, -64
; CHECK-NEXT:    .cfi_offset %r13, -56
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -176
; CHECK-NEXT:    .cfi_def_cfa_offset 336
; CHECK-NEXT:    lgr %r13, %r2
; CHECK-NEXT:    lg %r12, 0(%r2)
; CHECK-NEXT:    lg %r11, 0(%r2)
; CHECK-NEXT:    lg %r10, 0(%r2)
; CHECK-NEXT:    lg %r9, 0(%r2)
; CHECK-NEXT:    lg %r8, 0(%r2)
; CHECK-NEXT:    lg %r0, 0(%r2)
; CHECK-NEXT:    stg %r0, 168(%r15) # 8-byte Spill
; CHECK-NEXT:    lg %r0, 0(%r2)
; CHECK-NEXT:    stg %r0, 160(%r15) # 8-byte Spill
; CHECK-NEXT:    brasl %r14, g@PLT
; CHECK-NEXT:    stg %r12, 0(%r13)
; CHECK-NEXT:    stg %r11, 0(%r13)
; CHECK-NEXT:    stg %r10, 0(%r13)
; CHECK-NEXT:    stg %r9, 0(%r13)
; CHECK-NEXT:    stg %r8, 0(%r13)
; CHECK-NEXT:    lg %r0, 168(%r15) # 8-byte Reload
; CHECK-NEXT:    stg %r0, 0(%r13)
; CHECK-NEXT:    lg %r0, 160(%r15) # 8-byte Reload
; CHECK-NEXT:    stg %r0, 0(%r13)
; CHECK-NEXT:    lmg %r8, %r15, 240(%r15)
; CHECK-NEXT:    br %r14
  %v1 = load volatile i64, ptr %p
  %v2 = load volatile i64, ptr %p
  %v3 = load volatile i64, ptr %p
  %v4 = load volatile i64, ptr %p
  %v5 = load volatile i64, ptr %p
  %v6 = load volatile i64, ptr %p
  %v7 = load volatile i64, ptr %p
  call void @g()
  store volatile i64 %v1, ptr %p
  store volatile i64 %v2, ptr %p
  store volatile i64 %v3, ptr %p
  store volatile i64 %v4, ptr %p
  store volatile i64 %v5, ptr %p
  store volatile i64 %v6, ptr %p
  store volatile i64 %v7, ptr %p
  ret void
}

declare void @llvm.va_start(ptr)
declare void @use(ptr)

; The GPR varargs include %r7.
define void @f6(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e, ...) {
; CHECK-LABEL: f6:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r7, %r15, 56(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -192
; CHECK-NEXT:    .cfi_def_cfa_offset 352
; CHECK-NEXT:    la %r0, 192(%r15)
; CHECK-NEXT:    stg %r0, 184(%r15)
; CHECK-NEXT:    la %r0, 352(%r15)
; CHECK-NEXT:    stg %r0, 176(%r15)
; CHECK-NEXT:    mvghi 168(%r15), 0
; CHECK-NEXT:    la %r2, 160(%r15)
; CHECK-NEXT:    mvghi 160(%r15), 5
; CHECK-NEXT:    brasl %r14, use@PLT
; CHECK-NEXT:    lmg %r14, %r15, 304(%r15)
; CHECK-NEXT:    br %r14
  %va = alloca [4 x i64]
  call void @llvm.va_start(ptr %va)
  call void @use(ptr %va)
  ret void
}

define void @f7(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e, i64 %f, ...) {
; CHECK-LABEL: f7:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -192
; CHECK-NEXT:    .cfi_def_cfa_offset 352
; CHECK-NEXT:    la %r0, 192(%r15)
; CHECK-NEXT:    stg %r0, 184(%r15)
; CHECK-NEXT:    la %r0, 352(%r15)
; CHECK-NEXT:    stg %r0, 176(%r15)
; CHECK-NEXT:    mvghi 168(%r15), 0
; CHECK-NEXT:    la %r2, 160(%r15)
; CHECK-NEXT:    mvghi 160(%r15), 6
; CHECK-NEXT:    brasl %r14, use@PLT
; CHECK-NEXT:    lmg %r14, %r15, 304(%r15)
; CHECK-NEXT:    br %r14
  %va = alloca [4 x i64]
  call void @llvm.va_start(ptr %va)
  call void @use(ptr %va)
  ret void
}

; The address of an indirect argument can be in %r7.
declare void @g128(i64, i64, i64, i64, i64, i128)

define void @call_g128(i128 %a) {
; CHECK-LABEL: call_g128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -176
; CHECK-NEXT:    .cfi_def_cfa_offset 336
; CHECK-NEXT:    lg %r0, 8(%r2)
; CHECK-NEXT:    lg %r1, 0(%r2)
; CHECK-NEXT:    stg %r0, 168(%r15)
; CHECK-NEXT:    la %r7, 160(%r15)
; CHECK-NEXT:    lghi %r2, 1
; CHECK-NEXT:    lghi %r3, 2
; CHECK-NEXT:    lghi %r4, 3
; CHECK-NEXT:    lghi %r5, 4
; CHECK-NEXT:    lghi %r6, 5
; CHECK-NEXT:    stg %r1, 160(%r15)
; CHECK-NEXT:    brasl %r14, g128@PLT
; CHECK-NEXT:    lmg %r14, %r15, 288(%r15)
; CHECK-NEXT:    br %r14
  call void @g128(i64 1, i64 2, i64 3, i64 4, i64 5, i128 %a)
  ret void
}
