; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; Test the experimental kernel ABI tweak no-ext.
;
; RUN: llc < %s -mtriple=s390x-linux-gnu -mattr=+soft-float \
; RUN:   -mattr=+experimental-kernel-abi-no-ext -argext-abi-check \
; RUN:   | FileCheck %s

define i32 @f1(i32 %a) {
; CHECK-LABEL: f1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    br %r14
  ret i32 %a
}

define i64 @f2(i32 %a) {
; CHECK-LABEL: f2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lgfr %r2, %r2
; CHECK-NEXT:    br %r14
  %e = sext i32 %a to i64
  ret i64 %e
}

; Extension attributes are ignored.
define signext i32 @f3(i32 signext %a, i32 zeroext %b) {
; CHECK-LABEL: f3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ar %r2, %r3
; CHECK-NEXT:    br %r14
  %s = add i32 %a, %b
  ret i32 %s
}

define i64 @f4(i32 signext %a) {
; CHECK-LABEL: f4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    llgfr %r2, %r2
; CHECK-NEXT:    br %r14
  %e = zext i32 %a to i64
  ret i64 %e
}

declare signext i32 @g3(i32 signext, i8 zeroext)

define i64 @call_g3(i64 %a, i8 %b) {
; CHECK-LABEL: call_g3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    llcr %r3, %r3
; CHECK-NEXT:    # kill: def $r2l killed $r2l killed $r2d
; CHECK-NEXT:    brasl %r14, g3@PLT
; CHECK-NEXT:    lgfr %r2, %r2
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  %t = trunc i64 %a to i32
  %r = call signext i32 @g3(i32 %t, i8 %b)
  %e = sext i32 %r to i64
  ret i64 %e
}

; A narrow argument on the stack is right-justified.
define i64 @f5(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e, i32 %f, i8 %g) {
; CHECK-LABEL: f5:
; CHECK:       # %bb.0:
; CHECK-NEXT:    llgc %r2, 175(%r15)
; CHECK-NEXT:    agf %r2, 164(%r15)
; CHECK-NEXT:    br %r14
  %fe = sext i32 %f to i64
  %ge = zext i8 %g to i64
  %s = add i64 %fe, %ge
  ret i64 %s
}

declare void @g5(i64, i64, i64, i64, i64, i32, i8)

define void @call_g5(i32 %f, i8 %g) {
; CHECK-LABEL: call_g5:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r6, %r15, 48(%r15)
; CHECK-NEXT:    .cfi_offset %r6, -112
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -176
; CHECK-NEXT:    .cfi_def_cfa_offset 336
; CHECK-NEXT:    lr %r0, %r2
; CHECK-NEXT:    st %r3, 172(%r15)
; CHECK-NEXT:    lghi %r2, 1
; CHECK-NEXT:    lghi %r3, 2
; CHECK-NEXT:    lghi %r4, 3
; CHECK-NEXT:    lghi %r5, 4
; CHECK-NEXT:    lghi %r6, 5
; CHECK-NEXT:    st %r0, 164(%r15)
; CHECK-NEXT:    brasl %r14, g5@PLT
; CHECK-NEXT:    lmg %r6, %r15, 224(%r15)
; CHECK-NEXT:    br %r14
  call void @g5(i64 1, i64 2, i64 3, i64 4, i64 5, i32 %f, i8 %g)
  ret void
}

; The result of a libcall is not extended either.
define i64 @fptosi(float %f) {
; CHECK-LABEL: fptosi:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    brasl %r14, __fixsfsi@PLT
; CHECK-NEXT:    lgfr %r2, %r2
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  %r = fptosi float %f to i32
  %e = sext i32 %r to i64
  ret i64 %e
}

; _Bool is 0 or 1 in the low byte.
define i1 @bool_ret(i64 %a) {
; CHECK-LABEL: bool_ret:
; CHECK:       # %bb.0:
; CHECK-NEXT:    nilf %r2, 1
; CHECK-NEXT:    # kill: def $r2l killed $r2l killed $r2d
; CHECK-NEXT:    br %r14
  %t = trunc i64 %a to i1
  ret i1 %t
}

define i64 @bool_arg(i1 %a) {
; CHECK-LABEL: bool_arg:
; CHECK:       # %bb.0:
; CHECK-NEXT:    # kill: def $r2l killed $r2l def $r2d
; CHECK-NEXT:    risbg %r2, %r2, 63, 191, 0
; CHECK-NEXT:    br %r14
  %e = zext i1 %a to i64
  ret i64 %e
}

declare i1 @bool_g(i1)

define i64 @call_bool(i64 %a) {
; CHECK-LABEL: call_bool:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    nilf %r2, 1
; CHECK-NEXT:    # kill: def $r2l killed $r2l killed $r2d
; CHECK-NEXT:    brasl %r14, bool_g@PLT
; CHECK-NEXT:    # kill: def $r2l killed $r2l def $r2d
; CHECK-NEXT:    risbg %r2, %r2, 63, 191, 0
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  %t = trunc i64 %a to i1
  %r = call i1 @bool_g(i1 %t)
  %e = zext i1 %r to i64
  ret i64 %e
}
