; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; Test the experimental kernel ABI tweak struct-arg.
;
; RUN: llc < %s -mtriple=s390x-linux-gnu -mattr=+soft-float \
; RUN:   -mattr=+experimental-kernel-abi-struct-arg -argext-abi-check \
; RUN:   | FileCheck %s

; A pair after one scalar.
define i64 @f1(i64 %a, { i64, i64 } %b) {
; CHECK-LABEL: f1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    agr %r3, %r4
; CHECK-NEXT:    sgr %r3, %r2
; CHECK-NEXT:    lgr %r2, %r3
; CHECK-NEXT:    br %r14
  %b0 = extractvalue { i64, i64 } %b, 0
  %b1 = extractvalue { i64, i64 } %b, 1
  %s = add i64 %b0, %b1
  %t = sub i64 %s, %a
  ret i64 %t
}

; A pair in %r5:%r6.
define i64 @f2(i64 %a, i64 %b, i64 %c, { i64, i32 } %d) {
; CHECK-LABEL: f2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lgr %r2, %r5
; CHECK-NEXT:    algfr %r2, %r6
; CHECK-NEXT:    br %r14
  %d0 = extractvalue { i64, i32 } %d, 0
  %d1 = extractvalue { i64, i32 } %d, 1
  %ext = zext i32 %d1 to i64
  %s = add i64 %d0, %ext
  ret i64 %s
}

; Only %r6 is left, so the pair goes to the stack, and a later scalar
; takes %r6.  The 4-byte tail is left-justified in its slot.
define i64 @f3(i64 %a, i64 %b, i64 %c, i64 %d, { i64, i32 } %e, i64 %f) {
; CHECK-LABEL: f3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lg %r2, 160(%r15)
; CHECK-NEXT:    algf %r2, 168(%r15)
; CHECK-NEXT:    agr %r2, %r6
; CHECK-NEXT:    br %r14
  %e0 = extractvalue { i64, i32 } %e, 0
  %e1 = extractvalue { i64, i32 } %e, 1
  %ext = zext i32 %e1 to i64
  %s = add i64 %e0, %ext
  %t = add i64 %s, %f
  ret i64 %t
}

; A 3-byte tail on the stack.
define i64 @f4(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e, { i64, i24 } %f) {
; CHECK-LABEL: f4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    llgh %r0, 168(%r15)
; CHECK-NEXT:    sllg %r2, %r0, 8
; CHECK-NEXT:    ic %r2, 170(%r15)
; CHECK-NEXT:    br %r14
  %f1 = extractvalue { i64, i24 } %f, 1
  %ext = zext i24 %f1 to i64
  ret i64 %ext
}

; A 7-byte tail in a register.
define i64 @f5({ i64, i56 } %a) {
; CHECK-LABEL: f5:
; CHECK:       # %bb.0:
; CHECK-NEXT:    risbg %r2, %r3, 8, 191, 0
; CHECK-NEXT:    br %r14
  %a1 = extractvalue { i64, i56 } %a, 1
  %ext = zext i56 %a1 to i64
  ret i64 %ext
}

; Two pairs in registers, a third one on the stack.
define i64 @f6({ i64, i64 } %a, { i64, i64 } %b, { i64, i64 } %c) {
; CHECK-LABEL: f6:
; CHECK:       # %bb.0:
; CHECK-NEXT:    agr %r2, %r4
; CHECK-NEXT:    ag %r2, 168(%r15)
; CHECK-NEXT:    br %r14
  %a0 = extractvalue { i64, i64 } %a, 0
  %b0 = extractvalue { i64, i64 } %b, 0
  %c1 = extractvalue { i64, i64 } %c, 1
  %s = add i64 %a0, %b0
  %t = add i64 %s, %c1
  ret i64 %t
}

declare void @g3(i64, i64, i64, i64, { i64, i32 }, i64)

define void @call_f3(i64 %a, i32 %b) {
; CHECK-LABEL: call_f3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r6, %r15, 48(%r15)
; CHECK-NEXT:    .cfi_offset %r6, -112
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -176
; CHECK-NEXT:    .cfi_def_cfa_offset 336
; CHECK-NEXT:    lgr %r0, %r2
; CHECK-NEXT:    st %r3, 168(%r15)
; CHECK-NEXT:    lghi %r2, 1
; CHECK-NEXT:    lghi %r3, 2
; CHECK-NEXT:    lghi %r4, 3
; CHECK-NEXT:    lghi %r5, 4
; CHECK-NEXT:    lghi %r6, 5
; CHECK-NEXT:    stg %r0, 160(%r15)
; CHECK-NEXT:    brasl %r14, g3@PLT
; CHECK-NEXT:    lmg %r6, %r15, 224(%r15)
; CHECK-NEXT:    br %r14
  %p0 = insertvalue { i64, i32 } poison, i64 %a, 0
  %p1 = insertvalue { i64, i32 } %p0, i32 %b, 1
  call void @g3(i64 1, i64 2, i64 3, i64 4, { i64, i32 } %p1, i64 5)
  ret void
}

declare void @g4(i64, i64, i64, i64, i64, { i64, i24 })

define void @call_f4(i64 %a, i24 %b) {
; CHECK-LABEL: call_f4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r6, %r15, 48(%r15)
; CHECK-NEXT:    .cfi_offset %r6, -112
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -176
; CHECK-NEXT:    .cfi_def_cfa_offset 336
; CHECK-NEXT:    lgr %r0, %r2
; CHECK-NEXT:    lr %r1, %r3
; CHECK-NEXT:    srl %r1, 8
; CHECK-NEXT:    sth %r1, 168(%r15)
; CHECK-NEXT:    stc %r3, 170(%r15)
; CHECK-NEXT:    lghi %r2, 1
; CHECK-NEXT:    lghi %r3, 2
; CHECK-NEXT:    lghi %r4, 3
; CHECK-NEXT:    lghi %r5, 4
; CHECK-NEXT:    lghi %r6, 5
; CHECK-NEXT:    stg %r0, 160(%r15)
; CHECK-NEXT:    brasl %r14, g4@PLT
; CHECK-NEXT:    lmg %r6, %r15, 224(%r15)
; CHECK-NEXT:    br %r14
  %p0 = insertvalue { i64, i24 } poison, i64 %a, 0
  %p1 = insertvalue { i64, i24 } %p0, i24 %b, 1
  call void @g4(i64 1, i64 2, i64 3, i64 4, i64 5, { i64, i24 } %p1)
  ret void
}

declare void @g6(i64, { i64, i64 })

define void @call_f6(i64 %a, i64 %b) {
; CHECK-LABEL: call_f6:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lgr %r0, %r2
; CHECK-NEXT:    lghi %r2, 1
; CHECK-NEXT:    lgr %r4, %r3
; CHECK-NEXT:    lgr %r3, %r0
; CHECK-NEXT:    brasl %r14, g6@PLT
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  %p0 = insertvalue { i64, i64 } poison, i64 %a, 0
  %p1 = insertvalue { i64, i64 } %p0, i64 %b, 1
  call void @g6(i64 1, { i64, i64 } %p1)
  ret void
}

; A pair as a vararg.
declare void @gv(i64, ...)

define void @call_vararg(i64 %a, i64 %b) {
; CHECK-LABEL: call_vararg:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r6, %r15, 48(%r15)
; CHECK-NEXT:    .cfi_offset %r6, -112
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -176
; CHECK-NEXT:    .cfi_def_cfa_offset 336
; CHECK-NEXT:    lgr %r0, %r2
; CHECK-NEXT:    stg %r3, 168(%r15)
; CHECK-NEXT:    lghi %r2, 1
; CHECK-NEXT:    lghi %r3, 2
; CHECK-NEXT:    lghi %r4, 3
; CHECK-NEXT:    lghi %r5, 4
; CHECK-NEXT:    lghi %r6, 5
; CHECK-NEXT:    stg %r0, 160(%r15)
; CHECK-NEXT:    brasl %r14, gv@PLT
; CHECK-NEXT:    lmg %r6, %r15, 224(%r15)
; CHECK-NEXT:    br %r14
  %p0 = insertvalue { i64, i64 } poison, i64 %a, 0
  %p1 = insertvalue { i64, i64 } %p0, i64 %b, 1
  call void (i64, ...) @gv(i64 1, i64 2, i64 3, i64 4, { i64, i64 } %p1, i64 5)
  ret void
}
