; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; Test the experimental kernel ABI tweak no-rsa.
;
; RUN: llc < %s -mtriple=s390x-linux-gnu \
; RUN:   -mattr=+soft-float,+backchain,+experimental-kernel-abi-no-rsa \
; RUN:   | FileCheck %s --check-prefixes=CHECK,R6
; RUN: llc < %s -mtriple=s390x-linux-gnu \
; RUN:   -mattr=+soft-float,+backchain,+experimental-kernel-abi-no-rsa \
; RUN:   -mattr=+experimental-kernel-abi-r6-clobbered \
; RUN:   -mattr=+experimental-kernel-abi-r7-arg \
; RUN:   | FileCheck %s --check-prefixes=CHECK,R7

declare void @g()
declare void @g6(i64, i64, i64, i64, i64, i64)
declare void @g7(i64, i64, i64, i64, i64, i64, i64)

; The first stack argument is at 120(%r15).
define i64 @f1(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e, i64 %f, i64 %g) #0 {
; R6-LABEL: f1:
; R6:       # %bb.0:
; R6-NEXT:    lg %r2, 120(%r15)
; R6-NEXT:    ag %r2, 128(%r15)
; R6-NEXT:    br %r14
;
; R7-LABEL: f1:
; R7:       # %bb.0:
; R7-NEXT:    lgr %r2, %r7
; R7-NEXT:    ag %r2, 120(%r15)
; R7-NEXT:    br %r14
  %s = add i64 %f, %g
  ret i64 %s
}

define void @call_g7() #0 {
; R6-LABEL: call_g7:
; R6:       # %bb.0:
; R6-NEXT:    stmg %r6, %r15, 32(%r15)
; R6-NEXT:    .cfi_offset %r6, -128
; R6-NEXT:    .cfi_offset %r14, -64
; R6-NEXT:    .cfi_offset %r15, -56
; R6-NEXT:    lgr %r1, %r15
; R6-NEXT:    aghi %r15, -104
; R6-NEXT:    .cfi_def_cfa_offset 264
; R6-NEXT:    stg %r1, 112(%r15)
; R6-NEXT:    mvghi 128(%r15), 7
; R6-NEXT:    lghi %r2, 1
; R6-NEXT:    lghi %r3, 2
; R6-NEXT:    lghi %r4, 3
; R6-NEXT:    lghi %r5, 4
; R6-NEXT:    lghi %r6, 5
; R6-NEXT:    mvghi 120(%r15), 6
; R6-NEXT:    brasl %r14, g7@PLT
; R6-NEXT:    lmg %r6, %r15, 136(%r15)
; R6-NEXT:    br %r14
;
; R7-LABEL: call_g7:
; R7:       # %bb.0:
; R7-NEXT:    stmg %r14, %r15, 96(%r15)
; R7-NEXT:    .cfi_offset %r14, -64
; R7-NEXT:    .cfi_offset %r15, -56
; R7-NEXT:    lgr %r1, %r15
; R7-NEXT:    aghi %r15, -32
; R7-NEXT:    .cfi_def_cfa_offset 192
; R7-NEXT:    stg %r1, 112(%r15)
; R7-NEXT:    lghi %r2, 1
; R7-NEXT:    lghi %r3, 2
; R7-NEXT:    lghi %r4, 3
; R7-NEXT:    lghi %r5, 4
; R7-NEXT:    lghi %r6, 5
; R7-NEXT:    lghi %r7, 6
; R7-NEXT:    mvghi 120(%r15), 7
; R7-NEXT:    brasl %r14, g7@PLT
; R7-NEXT:    lmg %r14, %r15, 128(%r15)
; R7-NEXT:    br %r14
  call void @g7(i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7)
  ret void
}

; %r14 and %r15 are saved at 96, the backchain at 112.
define void @f2() #0 {
; CHECK-LABEL: f2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 96(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -64
; CHECK-NEXT:    .cfi_offset %r15, -56
; CHECK-NEXT:    lgr %r1, %r15
; CHECK-NEXT:    aghi %r15, -24
; CHECK-NEXT:    .cfi_def_cfa_offset 184
; CHECK-NEXT:    stg %r1, 112(%r15)
; CHECK-NEXT:    brasl %r14, g@PLT
; CHECK-NEXT:    lmg %r14, %r15, 120(%r15)
; CHECK-NEXT:    br %r14
  call void @g()
  ret void
}

; A local next to the register saves.
define void @f3() #0 {
; CHECK-LABEL: f3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 96(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -64
; CHECK-NEXT:    .cfi_offset %r15, -56
; CHECK-NEXT:    lgr %r1, %r15
; CHECK-NEXT:    aghi %r15, -32
; CHECK-NEXT:    .cfi_def_cfa_offset 192
; CHECK-NEXT:    stg %r1, 112(%r15)
; CHECK-NEXT:    mvghi 120(%r15), 0
; CHECK-NEXT:    brasl %r14, g@PLT
; CHECK-NEXT:    lmg %r14, %r15, 128(%r15)
; CHECK-NEXT:    br %r14
  %a = alloca i64
  store volatile i64 0, ptr %a
  call void @g()
  ret void
}

declare void @llvm.va_start(ptr)
declare void @use(ptr)

; The GPR varargs are saved from 0, and the overflow area is at incoming
; %r15 + 120.
define void @f4(i64 %a, ...) #0 {
; R6-LABEL: f4:
; R6:       # %bb.0:
; R6-NEXT:    stmg %r3, %r15, 8(%r15)
; R6-NEXT:    .cfi_offset %r6, -128
; R6-NEXT:    .cfi_offset %r14, -64
; R6-NEXT:    .cfi_offset %r15, -56
; R6-NEXT:    lgr %r1, %r15
; R6-NEXT:    aghi %r15, -168
; R6-NEXT:    .cfi_def_cfa_offset 328
; R6-NEXT:    stg %r1, 112(%r15)
; R6-NEXT:    la %r0, 152(%r15)
; R6-NEXT:    stg %r0, 144(%r15)
; R6-NEXT:    la %r0, 288(%r15)
; R6-NEXT:    stg %r0, 136(%r15)
; R6-NEXT:    mvghi 128(%r15), 0
; R6-NEXT:    la %r2, 120(%r15)
; R6-NEXT:    mvghi 120(%r15), 1
; R6-NEXT:    brasl %r14, use@PLT
; R6-NEXT:    lmg %r6, %r15, 200(%r15)
; R6-NEXT:    br %r14
;
; R7-LABEL: f4:
; R7:       # %bb.0:
; R7-NEXT:    stmg %r3, %r15, 8(%r15)
; R7-NEXT:    .cfi_offset %r14, -64
; R7-NEXT:    .cfi_offset %r15, -56
; R7-NEXT:    lgr %r1, %r15
; R7-NEXT:    aghi %r15, -168
; R7-NEXT:    .cfi_def_cfa_offset 328
; R7-NEXT:    stg %r1, 112(%r15)
; R7-NEXT:    la %r0, 152(%r15)
; R7-NEXT:    stg %r0, 144(%r15)
; R7-NEXT:    la %r0, 288(%r15)
; R7-NEXT:    stg %r0, 136(%r15)
; R7-NEXT:    mvghi 128(%r15), 0
; R7-NEXT:    la %r2, 120(%r15)
; R7-NEXT:    mvghi 120(%r15), 1
; R7-NEXT:    brasl %r14, use@PLT
; R7-NEXT:    lmg %r14, %r15, 264(%r15)
; R7-NEXT:    br %r14
  %va = alloca [4 x i64]
  call void @llvm.va_start(ptr %va)
  call void @use(ptr %va)
  ret void
}

declare ptr @llvm.frameaddress(i32)
declare ptr @llvm.returnaddress(i32)

define ptr @fa0() #0 {
; CHECK-LABEL: fa0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    la %r2, 112(%r15)
; CHECK-NEXT:    br %r14
  %r = call ptr @llvm.frameaddress(i32 0)
  ret ptr %r
}

define ptr @fa1() #0 {
; CHECK-LABEL: fa1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lghi %r2, 112
; CHECK-NEXT:    ag %r2, 112(%r15)
; CHECK-NEXT:    br %r14
  %r = call ptr @llvm.frameaddress(i32 1)
  ret ptr %r
}

define ptr @ra1() #0 {
; CHECK-LABEL: ra1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lg %r1, 112(%r15)
; CHECK-NEXT:    lg %r2, 96(%r1)
; CHECK-NEXT:    br %r14
  %r = call ptr @llvm.returnaddress(i32 1)
  ret ptr %r
}

; A dynamic allocation is above the 120-byte area.
define void @dyn(i64 %n) #0 {
; CHECK-LABEL: dyn:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r11, %r15, 72(%r15)
; CHECK-NEXT:    .cfi_offset %r11, -88
; CHECK-NEXT:    .cfi_offset %r14, -64
; CHECK-NEXT:    .cfi_offset %r15, -56
; CHECK-NEXT:    lgr %r1, %r15
; CHECK-NEXT:    aghi %r15, -48
; CHECK-NEXT:    .cfi_def_cfa_offset 208
; CHECK-NEXT:    stg %r1, 112(%r15)
; CHECK-NEXT:    lgr %r11, %r15
; CHECK-NEXT:    .cfi_def_cfa_register %r11
; CHECK-NEXT:    lgr %r1, %r15
; CHECK-NEXT:    la %r0, 7(%r2)
; CHECK-NEXT:    lg %r3, 112(%r15)
; CHECK-NEXT:    nill %r0, 65528
; CHECK-NEXT:    sgr %r1, %r0
; CHECK-NEXT:    lgr %r15, %r1
; CHECK-NEXT:    la %r2, 120(%r1)
; CHECK-NEXT:    stg %r3, 112(%r1)
; CHECK-NEXT:    brasl %r14, use@PLT
; CHECK-NEXT:    lmg %r11, %r15, 120(%r11)
; CHECK-NEXT:    br %r14
  %a = alloca i8, i64 %n
  call void @use(ptr %a)
  ret void
}

attributes #0 = { "packed-stack" }
