; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; Test the experimental kernel ABI tweak struct-ret.
;
; RUN: llc < %s -mtriple=s390x-linux-gnu -mattr=+soft-float \
; RUN:   -mattr=+experimental-kernel-abi-struct-ret -argext-abi-check \
; RUN:   | FileCheck %s

define { i64, i32 } @ret_pair_i32(i64 %a, i32 noext %b) {
; CHECK-LABEL: ret_pair_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    br %r14
  %r0 = insertvalue { i64, i32 } poison, i64 %a, 0
  %r1 = insertvalue { i64, i32 } %r0, i32 %b, 1
  ret { i64, i32 } %r1
}

define { i64, i24 } @ret_pair_i24(i64 %a, i64 %b) {
; CHECK-LABEL: ret_pair_i24:
; CHECK:       # %bb.0:
; CHECK-NEXT:    # kill: def $r3l killed $r3l killed $r3d
; CHECK-NEXT:    br %r14
  %t = trunc i64 %b to i24
  %r0 = insertvalue { i64, i24 } poison, i64 %a, 0
  %r1 = insertvalue { i64, i24 } %r0, i24 %t, 1
  ret { i64, i24 } %r1
}

define { i64, i64 } @ret_pair_i64(i64 %a, i64 %b) {
; CHECK-LABEL: ret_pair_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lgr %r0, %r2
; CHECK-NEXT:    lgr %r2, %r3
; CHECK-NEXT:    lgr %r3, %r0
; CHECK-NEXT:    br %r14
  %r0 = insertvalue { i64, i64 } poison, i64 %b, 0
  %r1 = insertvalue { i64, i64 } %r0, i64 %a, 1
  ret { i64, i64 } %r1
}

define noext i24 @ret_one_i24(i64 %a) {
; CHECK-LABEL: ret_one_i24:
; CHECK:       # %bb.0:
; CHECK-NEXT:    # kill: def $r2l killed $r2l killed $r2d
; CHECK-NEXT:    br %r14
  %t = trunc i64 %a to i24
  ret i24 %t
}

define i40 @ret_one_i40(i64 %a) {
; CHECK-LABEL: ret_one_i40:
; CHECK:       # %bb.0:
; CHECK-NEXT:    br %r14
  %t = trunc i64 %a to i40
  ret i40 %t
}

declare { i64, i32 } @pair_i32()

define i64 @call_pair_i32() {
; CHECK-LABEL: call_pair_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    brasl %r14, pair_i32@PLT
; CHECK-NEXT:    algfr %r2, %r3
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  %r = call { i64, i32 } @pair_i32()
  %a = extractvalue { i64, i32 } %r, 0
  %b = extractvalue { i64, i32 } %r, 1
  %bx = zext i32 %b to i64
  %s = add i64 %a, %bx
  ret i64 %s
}

declare { i64, i64 } @pair_i64()

define void @call_pair_i64(ptr %p) {
; CHECK-LABEL: call_pair_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r13, %r15, 104(%r15)
; CHECK-NEXT:    .cfi_offset %r13, -56
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lgr %r13, %r2
; CHECK-NEXT:    brasl %r14, pair_i64@PLT
; CHECK-NEXT:    stg %r2, 0(%r13)
; CHECK-NEXT:    stg %r3, 8(%r13)
; CHECK-NEXT:    lmg %r13, %r15, 264(%r15)
; CHECK-NEXT:    br %r14
  %r = call { i64, i64 } @pair_i64()
  store { i64, i64 } %r, ptr %p
  ret void
}
