; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; Test the experimental kernel ABI tweak even-pairs.
;
; RUN: llc < %s -mtriple=s390x-linux-gnu -mattr=+soft-float \
; RUN:   -mattr=+experimental-kernel-abi-struct-arg \
; RUN:   -mattr=+experimental-kernel-abi-int128 \
; RUN:   -mattr=+experimental-kernel-abi-even-pairs \
; RUN:   | FileCheck %s --check-prefixes=CHECK,R6
; RUN: llc < %s -mtriple=s390x-linux-gnu -mattr=+soft-float \
; RUN:   -mattr=+experimental-kernel-abi-struct-arg \
; RUN:   -mattr=+experimental-kernel-abi-int128 \
; RUN:   -mattr=+experimental-kernel-abi-even-pairs \
; RUN:   -mattr=+experimental-kernel-abi-r6-clobbered \
; RUN:   -mattr=+experimental-kernel-abi-r7-arg \
; RUN:   | FileCheck %s --check-prefixes=CHECK,R7

; %r3 is skipped, and a later scalar does not use it.
define i64 @f1(i64 %a, i128 %b, i64 %c) {
; CHECK-LABEL: f1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lgr %r2, %r5
; CHECK-NEXT:    agr %r2, %r6
; CHECK-NEXT:    br %r14
  %t = trunc i128 %b to i64
  %s = add i64 %t, %c
  ret i64 %s
}

define i64 @f2(i64 %a, { i64, i32 } %b, i64 %c) {
; CHECK-LABEL: f2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lgr %r2, %r4
; CHECK-NEXT:    agr %r2, %r6
; CHECK-NEXT:    br %r14
  %b0 = extractvalue { i64, i32 } %b, 0
  %s = add i64 %b0, %c
  ret i64 %s
}

; Without r7-arg, the pair goes to the stack, and %r5 and %r6 remain
; available.  With r7-arg, it is in %r6:%r7.
define i64 @f3(i64 %a, i64 %b, i64 %c, i128 %d, i64 %e, i64 %f) {
; R6-LABEL: f3:
; R6:       # %bb.0:
; R6-NEXT:    lgr %r2, %r5
; R6-NEXT:    ag %r2, 168(%r15)
; R6-NEXT:    agr %r2, %r6
; R6-NEXT:    br %r14
;
; R7-LABEL: f3:
; R7:       # %bb.0:
; R7-NEXT:    lgr %r2, %r7
; R7-NEXT:    ag %r2, 160(%r15)
; R7-NEXT:    ag %r2, 168(%r15)
; R7-NEXT:    br %r14
  %t = trunc i128 %d to i64
  %s = add i64 %t, %e
  %u = add i64 %s, %f
  ret i64 %u
}

declare void @g3(i64, i64, i64, i128, i64, i64)

define void @call_g3(i128 %a) {
; R6-LABEL: call_g3:
; R6:       # %bb.0:
; R6-NEXT:    stmg %r6, %r15, 48(%r15)
; R6-NEXT:    .cfi_offset %r6, -112
; R6-NEXT:    .cfi_offset %r14, -48
; R6-NEXT:    .cfi_offset %r15, -40
; R6-NEXT:    aghi %r15, -176
; R6-NEXT:    .cfi_def_cfa_offset 336
; R6-NEXT:    lgr %r0, %r2
; R6-NEXT:    stg %r3, 168(%r15)
; R6-NEXT:    lghi %r2, 1
; R6-NEXT:    lghi %r3, 2
; R6-NEXT:    lghi %r4, 3
; R6-NEXT:    lghi %r5, 4
; R6-NEXT:    lghi %r6, 5
; R6-NEXT:    stg %r0, 160(%r15)
; R6-NEXT:    brasl %r14, g3@PLT
; R6-NEXT:    lmg %r6, %r15, 224(%r15)
; R6-NEXT:    br %r14
;
; R7-LABEL: call_g3:
; R7:       # %bb.0:
; R7-NEXT:    stmg %r14, %r15, 112(%r15)
; R7-NEXT:    .cfi_offset %r14, -48
; R7-NEXT:    .cfi_offset %r15, -40
; R7-NEXT:    aghi %r15, -176
; R7-NEXT:    .cfi_def_cfa_offset 336
; R7-NEXT:    lgr %r7, %r3
; R7-NEXT:    lgr %r6, %r2
; R7-NEXT:    mvghi 168(%r15), 5
; R7-NEXT:    lghi %r2, 1
; R7-NEXT:    lghi %r3, 2
; R7-NEXT:    lghi %r4, 3
; R7-NEXT:    mvghi 160(%r15), 4
; R7-NEXT:    brasl %r14, g3@PLT
; R7-NEXT:    lmg %r14, %r15, 288(%r15)
; R7-NEXT:    br %r14
  call void @g3(i64 1, i64 2, i64 3, i128 %a, i64 4, i64 5)
  ret void
}

declare void @llvm.va_start(ptr)
declare void @use(ptr)

; va_start skips %r3.
define void @f4(i64 %a, i128 %b, ...) {
; R6-LABEL: f4:
; R6:       # %bb.0:
; R6-NEXT:    stmg %r6, %r15, 48(%r15)
; R6-NEXT:    .cfi_offset %r6, -112
; R6-NEXT:    .cfi_offset %r14, -48
; R6-NEXT:    .cfi_offset %r15, -40
; R6-NEXT:    aghi %r15, -192
; R6-NEXT:    .cfi_def_cfa_offset 352
; R6-NEXT:    la %r0, 192(%r15)
; R6-NEXT:    stg %r0, 184(%r15)
; R6-NEXT:    la %r0, 352(%r15)
; R6-NEXT:    stg %r0, 176(%r15)
; R6-NEXT:    mvghi 168(%r15), 0
; R6-NEXT:    la %r2, 160(%r15)
; R6-NEXT:    mvghi 160(%r15), 4
; R6-NEXT:    brasl %r14, use@PLT
; R6-NEXT:    lmg %r6, %r15, 240(%r15)
; R6-NEXT:    br %r14
;
; R7-LABEL: f4:
; R7:       # %bb.0:
; R7-NEXT:    stmg %r6, %r15, 48(%r15)
; R7-NEXT:    .cfi_offset %r14, -48
; R7-NEXT:    .cfi_offset %r15, -40
; R7-NEXT:    aghi %r15, -192
; R7-NEXT:    .cfi_def_cfa_offset 352
; R7-NEXT:    la %r0, 192(%r15)
; R7-NEXT:    stg %r0, 184(%r15)
; R7-NEXT:    la %r0, 352(%r15)
; R7-NEXT:    stg %r0, 176(%r15)
; R7-NEXT:    mvghi 168(%r15), 0
; R7-NEXT:    la %r2, 160(%r15)
; R7-NEXT:    mvghi 160(%r15), 4
; R7-NEXT:    brasl %r14, use@PLT
; R7-NEXT:    lmg %r14, %r15, 304(%r15)
; R7-NEXT:    br %r14
  %va = alloca [4 x i64]
  call void @llvm.va_start(ptr %va)
  call void @use(ptr %va)
  ret void
}

; A vararg pair after one scalar.
declare void @gv(i64, ...)

define void @call_vararg(i128 %a) {
; R6-LABEL: call_vararg:
; R6:       # %bb.0:
; R6-NEXT:    stmg %r6, %r15, 48(%r15)
; R6-NEXT:    .cfi_offset %r6, -112
; R6-NEXT:    .cfi_offset %r14, -48
; R6-NEXT:    .cfi_offset %r15, -40
; R6-NEXT:    aghi %r15, -160
; R6-NEXT:    .cfi_def_cfa_offset 320
; R6-NEXT:    lgr %r4, %r2
; R6-NEXT:    lghi %r2, 1
; R6-NEXT:    lghi %r6, 2
; R6-NEXT:    lgr %r5, %r3
; R6-NEXT:    brasl %r14, gv@PLT
; R6-NEXT:    lmg %r6, %r15, 208(%r15)
; R6-NEXT:    br %r14
;
; R7-LABEL: call_vararg:
; R7:       # %bb.0:
; R7-NEXT:    stmg %r14, %r15, 112(%r15)
; R7-NEXT:    .cfi_offset %r14, -48
; R7-NEXT:    .cfi_offset %r15, -40
; R7-NEXT:    aghi %r15, -160
; R7-NEXT:    .cfi_def_cfa_offset 320
; R7-NEXT:    lgr %r4, %r2
; R7-NEXT:    lghi %r2, 1
; R7-NEXT:    lghi %r6, 2
; R7-NEXT:    lgr %r5, %r3
; R7-NEXT:    brasl %r14, gv@PLT
; R7-NEXT:    lmg %r14, %r15, 272(%r15)
; R7-NEXT:    br %r14
  call void (i64, ...) @gv(i64 1, i128 %a, i64 2)
  ret void
}

; Libcalls too: the shift amount is in %r4.
define i128 @shl(i128 %a, i32 %b) {
; CHECK-LABEL: shl:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    llgfr %r4, %r4
; CHECK-NEXT:    brasl %r14, __ashlti3@PLT
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  %e = zext i32 %b to i128
  %r = shl i128 %a, %e
  ret i128 %r
}
