; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; Test the experimental kernel ABI tweak int128.
;
; RUN: llc < %s -mtriple=s390x-linux-gnu -mattr=+soft-float \
; RUN:   -mattr=+experimental-kernel-abi-int128 -argext-abi-check \
; RUN:   | FileCheck %s --check-prefixes=CHECK,SOFT
; RUN: llc < %s -mtriple=s390x-linux-gnu -mcpu=z13 \
; RUN:   -mattr=+experimental-kernel-abi-int128 -argext-abi-check \
; RUN:   | FileCheck %s --check-prefixes=CHECK,VECTOR

; In %r2:%r3, returned in %r2:%r3.
define i128 @f1(i128 %a) {
; SOFT-LABEL: f1:
; SOFT:       # %bb.0:
; SOFT-NEXT:    algfi %r3, 1
; SOFT-NEXT:    lghi %r0, 0
; SOFT-NEXT:    alcgr %r2, %r0
; SOFT-NEXT:    br %r14
;
; VECTOR-LABEL: f1:
; VECTOR:       # %bb.0:
; VECTOR-NEXT:    larl %r1, .LCPI0_0
; VECTOR-NEXT:    vl %v1, 0(%r1), 3
; VECTOR-NEXT:    vlvgp %v0, %r2, %r3
; VECTOR-NEXT:    vaq %v0, %v0, %v1
; VECTOR-NEXT:    vlgvg %r2, %v0, 0
; VECTOR-NEXT:    vlgvg %r3, %v0, 1
; VECTOR-NEXT:    br %r14
  %r = add i128 %a, 1
  ret i128 %r
}

; In %r3:%r4.
define i128 @f2(i64 %a, i128 %b) {
; CHECK-LABEL: f2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lgr %r2, %r3
; CHECK-NEXT:    lgr %r3, %r4
; CHECK-NEXT:    br %r14
  ret i128 %b
}

; In %r5:%r6.
define i64 @f3(i64 %a, i64 %b, i64 %c, i128 %d) {
; CHECK-LABEL: f3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lgr %r2, %r6
; CHECK-NEXT:    br %r14
  %t = trunc i128 %d to i64
  ret i64 %t
}

; Only %r6 is left, so the i128 goes to the stack, and a later i64 takes %r6.
define i64 @f4(i64 %a, i64 %b, i64 %c, i64 %d, i128 %e, i64 %f) {
; CHECK-LABEL: f4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lg %r2, 168(%r15)
; CHECK-NEXT:    ag %r2, 160(%r15)
; CHECK-NEXT:    agr %r2, %r6
; CHECK-NEXT:    br %r14
  %t = trunc i128 %e to i64
  %h0 = lshr i128 %e, 64
  %h = trunc i128 %h0 to i64
  %s = add i64 %t, %h
  %u = add i64 %s, %f
  ret i64 %u
}

declare i128 @g(i64, i128, i64, i64, i128, i64)

define i128 @call_g(i128 %a) {
; CHECK-LABEL: call_g:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r6, %r15, 48(%r15)
; CHECK-NEXT:    .cfi_offset %r6, -112
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -184
; CHECK-NEXT:    .cfi_def_cfa_offset 344
; CHECK-NEXT:    lgr %r4, %r3
; CHECK-NEXT:    lgr %r3, %r2
; CHECK-NEXT:    stg %r4, 168(%r15)
; CHECK-NEXT:    stg %r2, 160(%r15)
; CHECK-NEXT:    lghi %r2, 1
; CHECK-NEXT:    lghi %r5, 2
; CHECK-NEXT:    lghi %r6, 3
; CHECK-NEXT:    mvghi 176(%r15), 4
; CHECK-NEXT:    brasl %r14, g@PLT
; CHECK-NEXT:    lmg %r6, %r15, 232(%r15)
; CHECK-NEXT:    br %r14
  %r = call i128 @g(i64 1, i128 %a, i64 2, i64 3, i128 %a, i64 4)
  ret i128 %r
}

; Libcalls use the same convention.
define i128 @div(i128 %a, i128 %b) {
; CHECK-LABEL: div:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    brasl %r14, __divti3@PLT
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  %r = sdiv i128 %a, %b
  ret i128 %r
}

; fp128 keeps being passed and returned by reference.
define void @fadd(ptr %p, ptr %q) #0 {
; SOFT-LABEL: fadd:
; SOFT:       # %bb.0:
; SOFT-NEXT:    stmg %r13, %r15, 104(%r15)
; SOFT-NEXT:    .cfi_offset %r13, -56
; SOFT-NEXT:    .cfi_offset %r14, -48
; SOFT-NEXT:    .cfi_offset %r15, -40
; SOFT-NEXT:    aghi %r15, -192
; SOFT-NEXT:    .cfi_def_cfa_offset 352
; SOFT-NEXT:    lgr %r13, %r2
; SOFT-NEXT:    lg %r0, 8(%r3)
; SOFT-NEXT:    lg %r1, 0(%r3)
; SOFT-NEXT:    lg %r2, 8(%r2)
; SOFT-NEXT:    lg %r4, 0(%r13)
; SOFT-NEXT:    stg %r0, 168(%r15)
; SOFT-NEXT:    stg %r1, 160(%r15)
; SOFT-NEXT:    stg %r2, 184(%r15)
; SOFT-NEXT:    la %r2, 176(%r15)
; SOFT-NEXT:    la %r3, 160(%r15)
; SOFT-NEXT:    stg %r4, 176(%r15)
; SOFT-NEXT:    brasl %r14, __addtf3@PLT
; SOFT-NEXT:    stg %r2, 0(%r13)
; SOFT-NEXT:    stg %r3, 8(%r13)
; SOFT-NEXT:    lmg %r13, %r15, 296(%r15)
; SOFT-NEXT:    br %r14
;
; VECTOR-LABEL: fadd:
; VECTOR:       # %bb.0:
; VECTOR-NEXT:    stmg %r13, %r15, 104(%r15)
; VECTOR-NEXT:    .cfi_offset %r13, -56
; VECTOR-NEXT:    .cfi_offset %r14, -48
; VECTOR-NEXT:    .cfi_offset %r15, -40
; VECTOR-NEXT:    aghi %r15, -192
; VECTOR-NEXT:    .cfi_def_cfa_offset 352
; VECTOR-NEXT:    lgr %r13, %r2
; VECTOR-NEXT:    lg %r0, 0(%r2)
; VECTOR-NEXT:    lg %r1, 8(%r2)
; VECTOR-NEXT:    lg %r2, 0(%r3)
; VECTOR-NEXT:    lg %r3, 8(%r3)
; VECTOR-NEXT:    stg %r3, 168(%r15)
; VECTOR-NEXT:    stg %r2, 160(%r15)
; VECTOR-NEXT:    la %r2, 176(%r15)
; VECTOR-NEXT:    la %r3, 160(%r15)
; VECTOR-NEXT:    stg %r1, 184(%r15)
; VECTOR-NEXT:    stg %r0, 176(%r15)
; VECTOR-NEXT:    brasl %r14, __addtf3@PLT
; VECTOR-NEXT:    stg %r2, 0(%r13)
; VECTOR-NEXT:    stg %r3, 8(%r13)
; VECTOR-NEXT:    lmg %r13, %r15, 296(%r15)
; VECTOR-NEXT:    br %r14
  %a = load fp128, ptr %p
  %b = load fp128, ptr %q
  %r = fadd fp128 %a, %b
  store fp128 %r, ptr %p
  ret void
}

attributes #0 = { "target-features"="+soft-float" }
