; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; Test the experimental kernel ABI tweak struct-32.
;
; RUN: llc < %s -mtriple=s390x-linux-gnu -mattr=+soft-float \
; RUN:   -mattr=+experimental-kernel-abi-struct-ret \
; RUN:   -mattr=+experimental-kernel-abi-struct-arg \
; RUN:   -mattr=+experimental-kernel-abi-struct-32 -argext-abi-check \
; RUN:   | FileCheck %s
; RUN: llc < %s -mtriple=s390x-linux-gnu -mattr=+soft-float \
; RUN:   -mattr=+experimental-kernel-abi-struct-ret \
; RUN:   -mattr=+experimental-kernel-abi-struct-arg \
; RUN:   -mattr=+experimental-kernel-abi-struct-32 \
; RUN:   -mattr=+experimental-kernel-abi-int128 \
; RUN:   -mattr=+experimental-kernel-abi-even-pairs -argext-abi-check \
; RUN:   | FileCheck %s

; Four GPRs, and a later scalar in %r6.
define { i64, i64, i64, i32 } @f1({ i64, i64, i64, i32 } %a, i64 %b) {
; CHECK-LABEL: f1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lgr %r2, %r6
; CHECK-NEXT:    br %r14
  %r = insertvalue { i64, i64, i64, i32 } %a, i64 %b, 0
  ret { i64, i64, i64, i32 } %r
}

; Three GPRs starting at %r3, even with even-pairs.
define i64 @f2(i64 %a, { i64, i64, i24 } %b) {
; CHECK-LABEL: f2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    # kill: def $r5l killed $r5l def $r5d
; CHECK-NEXT:    risbg %r2, %r5, 40, 191, 0
; CHECK-NEXT:    br %r14
  %b2 = extractvalue { i64, i64, i24 } %b, 2
  %e = zext i24 %b2 to i64
  ret i64 %e
}

; Only two GPRs are left, so the composite goes to the stack as its memory
; image, and a later scalar takes %r5.
define i64 @f3(i64 %a, i64 %b, i64 %c, { i64, i64, i32 } %d, i64 %e) {
; CHECK-LABEL: f3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lg %r2, 160(%r15)
; CHECK-NEXT:    algf %r2, 176(%r15)
; CHECK-NEXT:    agr %r2, %r5
; CHECK-NEXT:    br %r14
  %d0 = extractvalue { i64, i64, i32 } %d, 0
  %d2 = extractvalue { i64, i64, i32 } %d, 2
  %x = zext i32 %d2 to i64
  %s = add i64 %d0, %x
  %t = add i64 %s, %e
  ret i64 %t
}

declare { i64, i64, i64, i64 } @g4(i64, i64, i64, { i64, i64, i32 }, i64)

define i64 @call_g4(i64 %a, i32 %b) {
; CHECK-LABEL: call_g4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -184
; CHECK-NEXT:    .cfi_def_cfa_offset 344
; CHECK-NEXT:    lgr %r0, %r2
; CHECK-NEXT:    st %r3, 176(%r15)
; CHECK-NEXT:    stg %r2, 168(%r15)
; CHECK-NEXT:    lghi %r2, 1
; CHECK-NEXT:    lghi %r3, 2
; CHECK-NEXT:    lghi %r4, 3
; CHECK-NEXT:    lghi %r5, 4
; CHECK-NEXT:    stg %r0, 160(%r15)
; CHECK-NEXT:    brasl %r14, g4@PLT
; CHECK-NEXT:    lgr %r2, %r5
; CHECK-NEXT:    lmg %r14, %r15, 296(%r15)
; CHECK-NEXT:    br %r14
  %p0 = insertvalue { i64, i64, i32 } poison, i64 %a, 0
  %p1 = insertvalue { i64, i64, i32 } %p0, i64 %a, 1
  %p2 = insertvalue { i64, i64, i32 } %p1, i32 %b, 2
  %r = call { i64, i64, i64, i64 } @g4(i64 1, i64 2, i64 3, { i64, i64, i32 } %p2, i64 4)
  %r3 = extractvalue { i64, i64, i64, i64 } %r, 3
  ret i64 %r3
}
