; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; Test the experimental kernel ABI tweak r6-clobbered.
;
; RUN: llc < %s -mtriple=s390x-linux-gnu -mattr=+soft-float \
; RUN:   -mattr=+experimental-kernel-abi-r6-clobbered | FileCheck %s

declare void @g()
declare i64 @g5(i64, i64, i64, i64, i64)

; %r6 is not saved, and a value that lives across a call does not use it.
define i64 @f1(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e) {
; CHECK-LABEL: f1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r13, %r15, 104(%r15)
; CHECK-NEXT:    .cfi_offset %r13, -56
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lgr %r13, %r6
; CHECK-NEXT:    brasl %r14, g@PLT
; CHECK-NEXT:    lgr %r2, %r13
; CHECK-NEXT:    lmg %r13, %r15, 264(%r15)
; CHECK-NEXT:    br %r14
  call void @g()
  ret i64 %e
}

; A sibling call with five arguments.
define i64 @f2(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e) {
; CHECK-LABEL: f2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lgr %r0, %r3
; CHECK-NEXT:    lgr %r1, %r2
; CHECK-NEXT:    lgr %r2, %r6
; CHECK-NEXT:    lgr %r3, %r5
; CHECK-NEXT:    lgr %r5, %r0
; CHECK-NEXT:    lgr %r6, %r1
; CHECK-NEXT:    jg g5@PLT
  %r = tail call i64 @g5(i64 %e, i64 %d, i64 %c, i64 %b, i64 %a)
  ret i64 %r
}

; %r6 can be clobbered without saving it.
define i64 @f3(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e) {
; CHECK-LABEL: f3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r11, %r15, 88(%r15)
; CHECK-NEXT:    .cfi_offset %r11, -72
; CHECK-NEXT:    .cfi_offset %r12, -64
; CHECK-NEXT:    .cfi_offset %r13, -56
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lgr %r13, %r5
; CHECK-NEXT:    lgr %r12, %r4
; CHECK-NEXT:    lgr %r11, %r3
; CHECK-NEXT:    brasl %r14, g5@PLT
; CHECK-NEXT:    lghi %r6, 0
; CHECK-NEXT:    lgr %r3, %r11
; CHECK-NEXT:    lgr %r4, %r12
; CHECK-NEXT:    lgr %r5, %r13
; CHECK-NEXT:    brasl %r14, g5@PLT
; CHECK-NEXT:    lmg %r11, %r15, 248(%r15)
; CHECK-NEXT:    br %r14
  %r = call i64 @g5(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e)
  %s = call i64 @g5(i64 %r, i64 %b, i64 %c, i64 %d, i64 0)
  ret i64 %s
}

; The call-saved GPRs are %r7-%r15.
define void @f4(ptr %p) {
; CHECK-LABEL: f4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r7, %r15, 56(%r15)
; CHECK-NEXT:    .cfi_offset %r7, -104
; CHECK-NEXT:    .cfi_offset %r8, -96
; CHECK-NEXT:    .cfi_offset %r9, -88
; CHECK-NEXT:    .cfi_offset %r10, -80
; CHECK-NEXT:    .cfi_offset %r11, -72
; CHECK-NEXT:    .cfi_offset %r12, -64
; CHECK-NEXT:    .cfi_offset %r13, -56
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -176
; CHECK-NEXT:    .cfi_def_cfa_offset 336
; CHECK-NEXT:    lgr %r13, %r2
; CHECK-NEXT:    lg %r12, 0(%r2)
; CHECK-NEXT:    lg %r11, 0(%r2)
; CHECK-NEXT:    lg %r10, 0(%r2)
; CHECK-NEXT:    lg %r9, 0(%r2)
; CHECK-NEXT:    lg %r8, 0(%r2)
; CHECK-NEXT:    lg %r7, 0(%r2)
; CHECK-NEXT:    lg %r0, 0(%r2)
; CHECK-NEXT:    stg %r0, 168(%r15) # 8-byte Spill
; CHECK-NEXT:    lg %r0, 0(%r2)
; CHECK-NEXT:    stg %r0, 160(%r15) # 8-byte Spill
; CHECK-NEXT:    brasl %r14, g@PLT
; CHECK-NEXT:    stg %r12, 0(%r13)
; CHECK-NEXT:    stg %r11, 0(%r13)
; CHECK-NEXT:    stg %r10, 0(%r13)
; CHECK-NEXT:    stg %r9, 0(%r13)
; CHECK-NEXT:    stg %r8, 0(%r13)
; CHECK-NEXT:    stg %r7, 0(%r13)
; CHECK-NEXT:    lg %r0, 168(%r15) # 8-byte Reload
; CHECK-NEXT:    stg %r0, 0(%r13)
; CHECK-NEXT:    lg %r0, 160(%r15) # 8-byte Reload
; CHECK-NEXT:    stg %r0, 0(%r13)
; CHECK-NEXT:    lmg %r7, %r15, 232(%r15)
; CHECK-NEXT:    br %r14
  %v1 = load volatile i64, ptr %p
  %v2 = load volatile i64, ptr %p
  %v3 = load volatile i64, ptr %p
  %v4 = load volatile i64, ptr %p
  %v5 = load volatile i64, ptr %p
  %v6 = load volatile i64, ptr %p
  %v7 = load volatile i64, ptr %p
  %v8 = load volatile i64, ptr %p
  call void @g()
  store volatile i64 %v1, ptr %p
  store volatile i64 %v2, ptr %p
  store volatile i64 %v3, ptr %p
  store volatile i64 %v4, ptr %p
  store volatile i64 %v5, ptr %p
  store volatile i64 %v6, ptr %p
  store volatile i64 %v7, ptr %p
  store volatile i64 %v8, ptr %p
  ret void
}

declare void @llvm.va_start(ptr)
declare void @use(ptr)

; A vararg function that saves no call-saved GPR still stores the GPR
; varargs, and restores %r15 by adding the frame size.
define void @f5(i64 %a, ...) {
; CHECK-LABEL: f5:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r3, %r15, 24(%r15)
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -192
; CHECK-NEXT:    .cfi_def_cfa_offset 352
; CHECK-NEXT:    la %r0, 192(%r15)
; CHECK-NEXT:    stg %r0, 184(%r15)
; CHECK-NEXT:    la %r0, 352(%r15)
; CHECK-NEXT:    stg %r0, 176(%r15)
; CHECK-NEXT:    mvghi 160(%r15), 1
; CHECK-NEXT:    mvghi 168(%r15), 0
; CHECK-NEXT:    lg %r0, 192(%r15)
; CHECK-NEXT:    stg %r0, 160(%r15)
; CHECK-NEXT:    aghi %r15, 192
; CHECK-NEXT:    br %r14
  %va = alloca [4 x i64]
  call void @llvm.va_start(ptr %va)
  %p = getelementptr i8, ptr %va, i64 24
  %rsa = load ptr, ptr %p
  %v = load i64, ptr %rsa
  store volatile i64 %v, ptr %va
  ret void
}

define void @f6(i64 %a, ...) {
; CHECK-LABEL: f6:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r3, %r15, 24(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -192
; CHECK-NEXT:    .cfi_def_cfa_offset 352
; CHECK-NEXT:    la %r0, 192(%r15)
; CHECK-NEXT:    stg %r0, 184(%r15)
; CHECK-NEXT:    la %r0, 352(%r15)
; CHECK-NEXT:    stg %r0, 176(%r15)
; CHECK-NEXT:    mvghi 168(%r15), 0
; CHECK-NEXT:    la %r2, 160(%r15)
; CHECK-NEXT:    mvghi 160(%r15), 1
; CHECK-NEXT:    brasl %r14, use@PLT
; CHECK-NEXT:    lmg %r14, %r15, 304(%r15)
; CHECK-NEXT:    br %r14
  %va = alloca [4 x i64]
  call void @llvm.va_start(ptr %va)
  call void @use(ptr %va)
  ret void
}
